server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:osbdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    open-in-view: false

joinfaces:
  primefaces:
    theme: saga
  faces:
    project-stage: Production
